# Generated by Django 2.1.2 on 2019-03-06 00:24

from django.db import migrations, models
import django.db.models.deletion
import election.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Election',
            fields=[
                ('codename', models.SlugField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, verbose_name='election name')),
                ('voting_start', models.DateTimeField(verbose_name='voting start time')),
                ('voting_end', models.DateTimeField(verbose_name='voting end time')),
                ('has_nomination', models.BooleanField()),
                ('nomination_start', models.DateTimeField(blank=True, null=True, verbose_name='nomination start time')),
                ('nomination_end', models.DateTimeField(blank=True, null=True, verbose_name='nomination end time')),
            ],
        ),
        migrations.CreateModel(
            name='Nomination',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=50)),
                ('nickname', models.CharField(blank=True, max_length=50, null=True)),
                ('manifesto', models.TextField(verbose_name='nomination manifesto')),
                ('photo', models.ImageField(upload_to=election.models.nomination_image_file_name)),
                ('time', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('codename', models.SlugField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, verbose_name='position name')),
                ('description', models.TextField(verbose_name='position description')),
                ('sort_order', models.IntegerField(blank=True, null=True, verbose_name='position sort order')),
                ('election', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='election.Election')),
            ],
        ),
        migrations.CreateModel(
            name='Support',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('supporter', models.CharField(max_length=50)),
                ('time', models.DateTimeField(auto_now=True)),
                ('nomination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='election.Nomination')),
            ],
        ),
        migrations.AddField(
            model_name='nomination',
            name='position',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='election.Position', verbose_name='nomination position'),
        ),
    ]
