# Generated by Django 2.1.2 on 2019-03-10 12:18

from django.db import migrations, models
from ..models import Nomination
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('election', '0001_initial'),
    ]

    def fill_nomination_uuid(apps, schema_editor):
        for nomination in Nomination.objects.all():
            nomination.uuid = uuid.uuid4()
            nomination.save()

    operations = [
        migrations.AddField(
            model_name='nomination',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
        migrations.RunPython(fill_nomination_uuid),
        migrations.AlterField(
            model_name='nomination',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='nomination',
            unique_together={('username', 'position')},
        ),
        migrations.AlterUniqueTogether(
            name='support',
            unique_together={('nomination', 'supporter')},
        ),
    ]
