# Generated by Django 2.1.2 on 2019-03-10 12:18

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('election', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='nomination',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='nomination',
            unique_together={('username', 'position')},
        ),
        migrations.AlterUniqueTogether(
            name='support',
            unique_together={('nomination', 'supporter')},
        ),
    ]
