# Generated by Django 2.1.2 on 2019-03-19 23:37

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('election', '0002_auto_20190310_1218'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='election.Position')),
            ],
        ),
        migrations.CreateModel(
            name='Voter',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=50)),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='election.Position')),
            ],
        ),
        migrations.CreateModel(
            name='VoteRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.IntegerField()),
                ('nomination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='election.Nomination')),
                ('vote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='election.Vote')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='voter',
            unique_together={('username', 'position')},
        ),
    ]
