# Generated by Django 2.0.5 on 2018-09-16 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fbevents', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='fb_id',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
