# Generated by Django 2.0.5 on 2018-09-18 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fbevents', '0002_auto_20180916_1117'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='end_time',
            field=models.DateTimeField(null=True),
        ),
    ]
