# Generated by Django 2.0.5 on 2018-07-26 21:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecsswebauth', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='samluser',
            options={'permissions': (('is_ecs_user', 'The user is within ECS'),)},
        ),
    ]
