# Generated by Django 2.0.5 on 2018-08-25 23:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Society',
            fields=[
                ('codename', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('short_name', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=100)),
                ('logo_file', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('time', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('website', models.URLField()),
                ('fb_group', models.URLField()),
                ('fb_page', models.URLField()),
                ('twitter', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='SocietyLinks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('url', models.URLField()),
                ('society', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.Society')),
            ],
        ),
    ]
