# Generated by Django 2.0.5 on 2018-08-26 16:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_auto_20180826_0047'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sponsor',
            fields=[
                ('codename', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('level', models.CharField(choices=[('gold', 'gold'), ('silver', 'silver'), ('bronze', 'bronze')], max_length=20)),
                ('logo_file', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('website', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='SponsorLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('url', models.URLField()),
                ('sponsor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.Sponsor')),
            ],
        ),
        migrations.RenameModel(
            old_name='SocietyLinks',
            new_name='SocietyLink',
        ),
    ]
