# Generated by Django 2.1.2 on 2018-10-06 20:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_committeerolemember_role_short_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='committeerolemember',
            options={'verbose_name_plural': 'committee roles members'},
        ),
        migrations.AlterModelOptions(
            name='society',
            options={'verbose_name_plural': 'societies'},
        ),
        migrations.AlterModelOptions(
            name='societylink',
            options={'verbose_name_plural': 'societies links'},
        ),
        migrations.AlterModelOptions(
            name='sponsorlink',
            options={'verbose_name_plural': 'sponsors links'},
        ),
    ]
