# Generated by Django 2.1.2 on 2018-10-06 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_auto_20181006_2147'),
    ]

    operations = [
        migrations.AlterField(
            model_name='society',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='society',
            name='email',
            field=models.EmailField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='society',
            name='fb_group',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='society',
            name='fb_page',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='society',
            name='location',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='society',
            name='time',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='society',
            name='twitter',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='society',
            name='website',
            field=models.URLField(blank=True),
        ),
    ]
