# Generated by Django 2.2.1 on 2019-05-22 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0008_auto_20190509_1016'),
    ]

    operations = [
        migrations.AlterField(
            model_name='committeerolemember',
            name='member_nickname',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
