# Generated by Django 2.2.1 on 2019-08-01 10:32

from django.db import migrations, models
import website.models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0009_auto_20190522_1326'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='society',
            name='logo_file',
        ),
        migrations.AddField(
            model_name='society',
            name='logo',
            field=models.ImageField(default='', upload_to=website.models.society_logo_image_file_name),
            preserve_default=False,
        ),
    ]
