# Generated by Django 2.2.1 on 2019-08-01 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0010_auto_20190801_1132'),
    ]

    operations = [
        migrations.AddField(
            model_name='society',
            name='github',
            field=models.CharField(blank=True, max_length=100, verbose_name='GitHub username/orgnisation'),
        ),
        migrations.AddField(
            model_name='society',
            name='instagram',
            field=models.CharField(blank=True, max_length=100, verbose_name='Instagram username'),
        ),
        migrations.AddField(
            model_name='society',
            name='youtube',
            field=models.URLField(blank=True, verbose_name='YouTube URL'),
        ),
        migrations.AlterField(
            model_name='society',
            name='fb_group',
            field=models.URLField(blank=True, verbose_name='Facebook group URL'),
        ),
        migrations.AlterField(
            model_name='society',
            name='fb_page',
            field=models.URLField(blank=True, verbose_name='Facebook Page URL'),
        ),
        migrations.AlterField(
            model_name='society',
            name='twitter',
            field=models.CharField(blank=True, max_length=100, verbose_name='Twitter username'),
        ),
    ]
