# Generated by Django 2.0.5 on 2018-07-28 09:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auditlog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='auditlog',
            options={'permissions': (('view_auditlog', 'Can view auditlog'),)},
        ),
    ]
