# Generated by Django 2.1.2 on 2018-10-05 14:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auditlog', '0002_auto_20180728_1015'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='auditlog',
            options={},
        ),
    ]
