# Generated by Django 2.0.5 on 2018-06-23 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0002_auto_20180621_1537'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubmittedIpRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_hash', models.CharField(max_length=128)),
                ('time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='feedback',
            name='message',
            field=models.TextField(verbose_name='Feedback'),
        ),
        migrations.AlterField(
            model_name='response',
            name='message',
            field=models.TextField(verbose_name='Response'),
        ),
    ]
