# Generated by Django 2.0.5 on 2018-07-24 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0003_auto_20180623_1523'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='from_ecs',
            field=models.BooleanField(default=False),
        ),
    ]
