# Generated by Django 2.0.5 on 2018-07-27 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0004_feedback_from_ecs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='committee',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='response',
            name='committee',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
