# Generated by Django 2.0.5 on 2018-07-28 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0006_feedbackauditlog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedbackauditlog',
            name='action',
            field=models.CharField(choices=[('create', 'created'), ('edit', 'edited'), ('delet', 'deleted')], max_length=20),
        ),
    ]
