# Generated by Django 2.0.5 on 2018-09-11 22:34

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0007_auto_20180728_0930'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
