# Generated by Django 2.1.2 on 2018-10-15 23:30

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0009_alter_user_last_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codename', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('sort_order', models.IntegerField(blank=True, null=True)),
                ('paypal_button_id', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='ItemOption',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paypal_option_number', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(7)], verbose_name='PayPal option number')),
                ('paypal_option_name', models.CharField(max_length=20, verbose_name='PayPal option name')),
                ('name', models.CharField(max_length=20)),
                ('auto_value', models.CharField(blank=True, choices=[('username', 'Username')], max_length=20, null=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.Item')),
            ],
        ),
        migrations.CreateModel(
            name='ItemPermission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.Item')),
                ('permission', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='auth.Permission')),
            ],
        ),
        migrations.CreateModel(
            name='OptionChoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, null=True)),
                ('name', models.CharField(max_length=20)),
                ('value', models.CharField(max_length=20)),
                ('item_option', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.ItemOption')),
            ],
        ),
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('codename', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('start', models.DateTimeField()),
                ('end', models.DateTimeField()),
            ],
        ),
        migrations.AddField(
            model_name='item',
            name='sale',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='shop.Sale'),
        ),
    ]
