# Generated by Django 2.0.5 on 2018-09-16 13:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jumpstart', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Helper',
            fields=[
                ('username', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('nickname', models.CharField(max_length=50)),
                ('photo', models.ImageField(upload_to='jumpstart2018/helpers/')),
                ('group', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='jumpstart.Group')),
            ],
        ),
    ]
