# Generated by Django 2.0.5 on 2018-09-17 12:05

from django.db import migrations, models
import jumpstart.models
import jumpstart.validators


class Migration(migrations.Migration):

    dependencies = [
        ('jumpstart', '0004_auto_20180916_2216'),
    ]

    operations = [
        migrations.AlterField(
            model_name='helper',
            name='photo',
            field=models.ImageField(upload_to=jumpstart.models.helper_photo_file_name, validators=[jumpstart.validators.validate_photo_file_extension]),
        ),
    ]
