# Generated by Django 2.0.5 on 2018-09-21 23:31

from django.db import migrations, models
import jumpstart.models
import jumpstart.validators


class Migration(migrations.Migration):

    dependencies = [
        ('jumpstart', '0005_auto_20180917_1305'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='charity_shop_challenge_photo',
            field=models.ImageField(null=True, upload_to=jumpstart.models.charity_shop_challenge_photo_file_name, validators=[jumpstart.validators.validate_photo_file_extension]),
        ),
        migrations.AlterField(
            model_name='group',
            name='name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
