# Generated by Django 2.0.5 on 2018-09-23 06:37

from django.db import migrations, models
import jumpstart.models
import jumpstart.validators


class Migration(migrations.Migration):

    dependencies = [
        ('jumpstart', '0006_auto_20180922_0031'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='coding_challenge_score',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='group',
            name='mitre_challenge_score',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='group',
            name='stags_quiz_score',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='group',
            name='charity_shop_challenge_photo',
            field=models.ImageField(blank=True, null=True, upload_to=jumpstart.models.charity_shop_challenge_photo_file_name, validators=[jumpstart.validators.validate_photo_file_extension], verbose_name='Charity Shop Challenge photo'),
        ),
    ]
