# Generated by Django 2.0.5 on 2018-09-24 08:07

from django.db import migrations, models
import django.db.models.deletion
import jumpstart.models
import jumpstart.validators


class Migration(migrations.Migration):

    dependencies = [
        ('jumpstart', '0009_auto_20180923_2327'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScavengerHunt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to=jumpstart.models.scavenger_hunt_submission_photo_file_name, validators=[jumpstart.validators.validate_photo_file_extension])),
                ('group', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='jumpstart.Group')),
            ],
        ),
    ]
