# Generated by Django 2.2.1 on 2019-08-27 14:57

import django.core.validators
from django.db import migrations, models
import jumpstart.models
import jumpstart.validators


class Migration(migrations.Migration):

    dependencies = [
        ('jumpstart', '0011_auto_20180925_1229'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='number',
            field=models.PositiveSmallIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Group Number'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='group',
            name='charity_shop_challenge_photo',
            field=models.ImageField(blank=True, null=True, upload_to=jumpstart.models.charity_shop_challenge_photo_file_name, validators=[jumpstart.validators.validate_photo_file_extension], verbose_name='Charity Shop Challenge Photo'),
        ),
    ]
