# Generated by Django 2.2.1 on 2019-08-27 15:30

from django.db import migrations, models
import django.db.models.deletion
import jumpstart.models
import jumpstart.validators


class Migration(migrations.Migration):

    dependencies = [
        ('jumpstart', '0012_auto_20190827_1557'),
    ]

    operations = [
        migrations.RenameField(
            model_name='helper',
            old_name='nickname',
            new_name='prefered_name',
        ),
        migrations.AlterField(
            model_name='helper',
            name='prefered_name',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Preferend Name'),
        ),
        migrations.AlterField(
            model_name='helper',
            name='group',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='jumpstart.Group', verbose_name='Group'),
        ),
        migrations.AlterField(
            model_name='helper',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='helper',
            name='photo',
            field=models.ImageField(upload_to=jumpstart.models.helper_photo_file_name, validators=[jumpstart.validators.validate_photo_file_extension], verbose_name='Photo'),
        ),
        migrations.AlterField(
            model_name='helper',
            name='username',
            field=models.CharField(max_length=20, primary_key=True, serialize=False, verbose_name='Username'),
        ),
    ]
