# Generated by Django 2.2.1 on 2019-09-04 13:09

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('jumpstart', '0015_jumpstart'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='jumpstart',
            options={'verbose_name': 'Jumpstart', 'verbose_name_plural': 'Jumpstart'},
        ),
        migrations.AddField(
            model_name='jumpstart',
            name='helper_profile_lock_time',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Helper Profile Lock Time'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='helper',
            name='username',
            field=models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='Username'),
        ),
        migrations.AlterField(
            model_name='jumpstart',
            name='end_time',
            field=models.DateTimeField(verbose_name='End Time'),
        ),
        migrations.AlterField(
            model_name='jumpstart',
            name='start_time',
            field=models.DateTimeField(verbose_name='Start Time'),
        ),
    ]
