# Generated by Django 2.2.1 on 2019-09-05 09:50

from django.db import migrations, models
import uuid

from ..models import Fresher


def fill_freshers_uuid(apps, schema_editor):
    for row in Fresher.objects.all():
        row.uuid = uuid.uuid4()
        row.save()


class Migration(migrations.Migration):

    dependencies = [
        ('jumpstart', '0016_auto_20190904_1409'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fresher',
            options={'ordering': ['group', 'name']},
        ),
        migrations.AlterModelOptions(
            name='group',
            options={'ordering': ['number']},
        ),
        migrations.AlterModelOptions(
            name='helper',
            options={'ordering': ['group']},
        ),
        migrations.AddField(
            model_name='fresher',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, verbose_name='UUID'),
        ),
        migrations.RunPython(fill_freshers_uuid)
    ]
