# Generated by Django 2.2.1 on 2019-09-21 23:02

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import jumpstart.models
import jumpstart.validators
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('jumpstart', '0017_auto_20190905_1050'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fresher',
            options={'ordering': ['group__number', 'name']},
        ),
        migrations.AlterModelOptions(
            name='helper',
            options={'ordering': ['group__number']},
        ),
        migrations.RemoveField(
            model_name='group',
            name='charity_shop_challenge_photo',
        ),
        migrations.RemoveField(
            model_name='group',
            name='coding_challenge_score',
        ),
        migrations.RemoveField(
            model_name='group',
            name='games_challenge_score',
        ),
        migrations.RemoveField(
            model_name='group',
            name='mitre_challenge_score',
        ),
        migrations.RemoveField(
            model_name='group',
            name='sports_challenge_score',
        ),
        migrations.RemoveField(
            model_name='group',
            name='stags_quiz_score',
        ),
        migrations.AlterField(
            model_name='fresher',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='UUID'),
        ),
        migrations.AlterField(
            model_name='group',
            name='number',
            field=models.PositiveSmallIntegerField(unique=True, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Group Number'),
        ),
        migrations.AlterField(
            model_name='helper',
            name='preferred_name',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Preferred Name'),
        ),
        migrations.CreateModel(
            name='CharityShopChallengeSubmission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('photo', models.ImageField(blank=True, null=True, upload_to=jumpstart.models.charity_shop_challenge_photo_file_name, validators=[jumpstart.validators.validate_photo_file_extension], verbose_name='Charity Shop Challenge Photo')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='jumpstart.Group')),
            ],
        ),
    ]
